package com.nexters.bandalart.android.feature.home.model

// 임시 데이터
// 데이터의 구조를 파악 하기 위함
val bandalartData = BandalartCellUiModel(
  key = "6km1Z",
  title = "넥스터즈 1등하기",
  children = listOf(
    BandalartCellUiModel(
      key = "9nyXk",
      title = "iOS 출시",
      description = null,
      isCompleted = false,
      completionRatio = 65,
      parentKey = "6km1Z",
      children = listOf(
        BandalartCellUiModel(
          key = "WSl7R",
          title = "개발자 계정 만들기",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "9nyXk",
        ),
        BandalartCellUiModel(
          key = "X7Hz3",
          title = "MVP 개발",
          description = null,
          isCompleted = false,
          completionRatio = 0,
          parentKey = "9nyXk",
        ),
        BandalartCellUiModel(
          key = "5z1EG",
          title = null,
          description = null,
          isCompleted = false,
          completionRatio = 0,
          parentKey = "9nyXk",
        ),
        BandalartCellUiModel(
          key = "OzoOh",
          title = "코딩 컨벤션 정하기",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "9nyXk",
        ),
        BandalartCellUiModel(
          key = "zHKuD",
          title = "1일 1커밋",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "9nyXk",
        ),
      ),
    ),
    BandalartCellUiModel(
      key = "DoOMX",
      title = "Android 출시",
      description = null,
      isCompleted = true,
      completionRatio = 0,
      parentKey = "6km1Z",
      children = listOf(
        BandalartCellUiModel(
          key = "7G14I",
          title = "매일 밤새기",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "DoOMX",
        ),
        BandalartCellUiModel(
          key = "17i3r",
          title = "개발자 계정 만들기",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "DoOMX",
        ),
        BandalartCellUiModel(
          key = "RpV3q",
          title = "MVP 개발",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "DoOMX",
        ),
        BandalartCellUiModel(
          key = "JJMm7",
          title = "코딩 컨벤션 정하기",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "DoOMX",
        ),
        BandalartCellUiModel(
          key = "j53MX",
          title = "하나라도 더 만들기",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "DoOMX",
        ),
      ),
    ),
    BandalartCellUiModel(
      key = "Uvwfk",
      title = "PM 말듣기",
      description = null,
      isCompleted = false,
      completionRatio = 0,
      parentKey = "6km1Z",
      children = listOf(
        BandalartCellUiModel(
          key = "xL5dX",
          title = "화식",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "Uvwfk",
        ),
        BandalartCellUiModel(
          key = "kYdKc",
          title = "클라이밍",
          description = null,
          isCompleted = false,
          completionRatio = 0,
          parentKey = "Uvwfk",
        ),
        BandalartCellUiModel(
          key = "YA7dR",
          title = "카페",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "Uvwfk",
        ),
        BandalartCellUiModel(
          key = "RfD8f",
          title = "산책",
          description = null,
          isCompleted = false,
          completionRatio = 0,
          parentKey = "Uvwfk",
        ),
        BandalartCellUiModel(
          key = "1Fr4W",
          title = null,
          description = null,
          isCompleted = false,
          completionRatio = 0,
          parentKey = "Uvwfk",
        ),
      ),
    ),
    BandalartCellUiModel(
      key = "2tQw0",
      title = "넥나잇 준비",
      description = null,
      isCompleted = false,
      completionRatio = 0,
      parentKey = "6km1Z",
      children = listOf(
        BandalartCellUiModel(
          key = "vXZTa",
          title = "세면도구 챙기기",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "2tQw0",
        ),
        BandalartCellUiModel(
          key = "xmMxb",
          title = "라꾸라꾸 구매",
          description = null,
          isCompleted = false,
          completionRatio = 0,
          parentKey = "2tQw0",
        ),
        BandalartCellUiModel(
          key = "48G0Z",
          title = "노트북 충전기 챙기기",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "2tQw0",
        ),
        BandalartCellUiModel(
          key = "6fqqV",
          title = "담뇨 챙기기",
          description = null,
          isCompleted = false,
          completionRatio = 0,
          parentKey = "2tQw0",
        ),
        BandalartCellUiModel(
          key = "A3WwG",
          title = "커피 준비",
          description = null,
          isCompleted = true,
          completionRatio = 0,
          parentKey = "2tQw0",
        ),
      ),
    ),
  ),
)
