[versions]

android-gradle-plugin = "8.0.2"
gradle-dependency-handler-extensions = "1.1.0"

google-secrets = "2.0.1"
google-service = "4.3.14"

kotlin-core = "1.8.22"
kotlin-detekt = "1.23.0"
kotlin-ktlint-gradle = "11.5.0"
kotlin-ktlint-source = "0.48.2"

kotlinx-coroutines = "1.7.2"
kotlinx-datetime = "0.4.0"
kotlinx-serialization = "1.5.1"

android-hilt = "2.46.1"

androidx-appcompat = "1.6.1"
androidx-core = "1.10.1"
androidx-constraintlayout = "2.1.4"
androidx-datastore = "1.0.0"
androidx-lifecycle-runtime = "2.6.1"
androidx-splash = "1.0.1"
androidx-startup = "1.1.1"
androidx-activity-compose = "1.7.2"
androidx-compose-compiler = "1.4.8"
androidx-compose-bom = "2023.06.01"
androidx-compose-material3 = "1.2.0-alpha04"
androidx-compose-runtime-tracing = "1.0.0-alpha03"
androidx-compose-constraintlayout = "1.0.1"
androidx-compose-navigation = "2.6.0"
androidx-hilt-navigation-compose = "1.0.0"

coil = "2.4.0"
desugar-jdk = "2.0.3"
javax-inject = "1"
ktor-client = "2.3.2"
lottie-compose = "5.2.0"
timber = "5.0.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
facebook-shimmer = "0.5.0"
firebase-bom = "32.2.2"
firebase-crashlytics = "2.9.2"

[libraries]

gradle-android = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }

kotlin-ktlint = { group = "com.pinterest", name = "ktlint", version.ref = "kotlin-ktlint-source" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

android-hilt-compile = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "android-hilt" }
android-hilt-runtime = { group = "com.google.dagger", name = "hilt-android", version.ref = "android-hilt" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx.datastore" }
androidx-hilt-compose-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
androidx-splash = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-splash" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidx-startup" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle-runtime" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle-runtime" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidx-compose-constraintlayout" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-compose-material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-compose-navigation" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "androidx-compose-runtime-tracing" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor-client" }
ktor-client-engine-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor-client" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor-client" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor-client" }
ktor-client-json = { group = "io.ktor", name = "ktor-client-json", version.ref = "ktor-client" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor-client" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor-client" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }

desugar-jdk = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar-jdk" }
detekt-plugin-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "kotlin-detekt" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javax-inject" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie-compose" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
facebook-shimmer = { group = "com.facebook.shimmer", name = "shimmer", version.ref = "facebook-shimmer" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }

[plugins]

gradle-dependency-handler-extensions = { id = "land.sungbin.dependency.handler.extensions", version.ref = "gradle-dependency-handler-extensions" }

google-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "google-secrets" }
google-service = { id = "com.google.gms.google-services", version.ref = "google-service" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-core" }
kotlin-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "kotlin-detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-core" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-core" }
kotlin-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "kotlin-ktlint-gradle" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin-core" }

kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-core" }

android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
android-hilt = { id = "com.google.dagger.hilt.android", version.ref = "android-hilt" }

firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }

[bundles]

androidx-compose = [
    "androidx-compose-animation",
    "androidx-compose-foundation",
    "androidx-compose-foundation-layout",
    "androidx-compose-material-iconsExtended",
    "androidx-compose-material3",
    "androidx-compose-runtime",
    "androidx-compose-runtime-tracing",
    "androidx-compose-constraintlayout",
    "androidx-compose-navigation",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-ui-util",
]

androidx-lifecycle = [
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-compose",
]

ktor-client = [
    "ktor-client-core",
    "ktor-client-engine-cio",
    "ktor-client-content-negotiation",
    "ktor-client-okhttp",
    "ktor-client-json",
    "ktor-client-logging",
    "ktor-serialization",
]

coil = [
    "coil",
    "coil-compose",
    "coil-svg",
]
